// ═══════════════════════════════════════════════
// auto-blog.js — Autonomous bulk post generation
// ═══════════════════════════════════════════════
import { callAI }    from './ai-core.js';
import { sanitize, showToast, slugify, db, parseAIJson } from './config.js';
import { state }     from './state.js';
import { loadAll }   from './posts.js';
import { collection, addDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

function logItem(logId, msg, ok=true) {
  const el = document.getElementById(logId);
  if (!el) return;
  const div = document.createElement('div');
  div.className = `autoblog-log-item ${ok?'success':'error'}`;
  div.innerHTML = `<span>${ok?'✓':'✕'}</span><span>${msg}</span>`;
  el.insertBefore(div, el.firstChild);
}

window.runAutoBlog = async () => {
  const count    = parseInt(document.getElementById('abCount')?.value)||2;
  const category = document.getElementById('abCategory')?.value||'Fintech';
  const topicSeed= document.getElementById('abTopicSeed')?.value.trim()||`fintech trends ${new Date().getFullYear()}`;
  const pub      = document.getElementById('abPublishSwitch')?.classList.contains('on');
  const logEl    = document.getElementById('autoblogLog');
  const btn      = document.getElementById('btnAutoBlog');
  const btnTxt   = document.getElementById('abBtnTxt');
  const spinner  = document.getElementById('abSpinner');

  if (btn)     btn.disabled = true;
  if (btnTxt)  btnTxt.textContent = 'Running…';
  if (spinner) spinner.style.display = 'inline-block';
  if (logEl)   logEl.innerHTML = '';

  logItem('autoblogLog', `Starting — ${count} post(s) in ${category}…`);
  let done = 0;

  for (let i=0; i<count; i++) {
    // Step 1: generate topic
    const topicR = await callAI(
      `Generate a specific trending fintech article title related to "${topicSeed}" in ${category} for ${new Date().getFullYear()}. Return ONLY the title, nothing else.`,
      true
    );
    if (topicR.error) { logItem('autoblogLog', `Post ${i+1}: topic failed — ${topicR.error}`, false); continue; }
    const t = topicR.text.trim().replace(/^["']|["']$/g,'');
    logItem('autoblogLog', `Writing: "${t.substring(0,50)}…"`);

    // Step 2: write article
    const artR = await callAI(
      `Write a 700-900 word fintech blog post.\nTitle: "${t}"\nCategory: ${category}\nReturn ONLY clean HTML using <h2><h3><p><strong><ul><li> tags.`,
      true, 'auto', 4000
    );
    if (artR.error) { logItem('autoblogLog', `"${t.substring(0,30)}" — write failed`, false); continue; }

    // Step 3: generate metadata
    const metaR = await callAI(
      `For: "${t}" return ONLY JSON:\n{"summary":"2 sentences","tags":["t1","t2","t3"],"slug":"url-slug"}`,
      true
    );
    let meta = { summary:'', tags:[], slug:slugify(t) };
    const metaParsed = parseAIJson(metaR.error ? '' : metaR.text);
    if (metaParsed) meta = { ...meta, ...metaParsed };

    // Step 4: save to Firestore
    try {
      await addDoc(collection(db,'posts'), {
        title:t, excerpt:meta.summary, content:sanitize(artR.text),
        category, slug:meta.slug||slugify(t), metaDesc:meta.summary,
        tags:meta.tags||[], image:'', readingTime:4,
        published:pub, premium:false, autoGenerated:true,
        createdAt:serverTimestamp(), updatedAt:serverTimestamp()
      });
      done++;
      state.abSessionTotal++;
      if (pub) state.abSessionPublished++;
      logItem('autoblogLog', `"${t.substring(0,40)}" — ${pub?'Published ✓':'Saved as draft ✓'}`);
      const totalEl = document.getElementById('ab-total');
      const pubEl   = document.getElementById('ab-published');
      if (totalEl)  totalEl.textContent  = state.abSessionTotal;
      if (pubEl)    pubEl.textContent    = state.abSessionPublished;
    } catch(e) {
      logItem('autoblogLog', `Save failed: ${e.message}`, false);
    }

    if (i < count-1) await new Promise(r => setTimeout(r, 2500));
  }

  if (btn)     btn.disabled = false;
  if (btnTxt)  btnTxt.textContent = '🤖 Start Auto Blog';
  if (spinner) spinner.style.display = 'none';
  showToast(`Auto Blog done! ${done} post(s) created.`,'success');
  await loadAll();
};
